/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.controlCiudad;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import modelo.Ciudad;

/**
 *
 * @author john
 */
public class vistaCiudad extends javax.swing.JFrame {

    /**
     * Creates new form vistaCiudad
     */
    public vistaCiudad() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblCiudad = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txfCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        lblCodigoPais = new javax.swing.JLabel();
        txfCodigoPais = new javax.swing.JTextField();
        txfRutaNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListar = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnRutaNombre = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCiudad.setText("CIUDAD");
        getContentPane().add(lblCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 12, -1, -1));

        lblCodigo.setText("Codigo:");
        getContentPane().add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 54, -1, -1));
        getContentPane().add(txfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 48, 189, -1));

        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 102, -1, -1));
        getContentPane().add(txfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 96, 189, -1));

        lblCodigoPais.setText("Coigo país:");
        getContentPane().add(lblCodigoPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 150, -1, -1));
        getContentPane().add(txfCodigoPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 144, 189, -1));
        getContentPane().add(txfRutaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 193, 189, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 242, -1, -1));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 242, -1, -1));

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 242, -1, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 242, -1, -1));

        tblListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblListar);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 280, 306, 102));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 394, 308, -1));

        btnRutaNombre.setText("Cargar ruta");
        btnRutaNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaNombreActionPerformed(evt);
            }
        });
        getContentPane().add(btnRutaNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 192, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void listar(){
        Object[][] objMat;
        String[] vectTit;
        Ciudad objCiudad = new Ciudad("", "", "", "");
        control.controlCiudad objControlCiudad = new controlCiudad(objCiudad);
        String[][] mat=objControlCiudad.listar();
        
        objMat= new Object[mat.length][mat[0].length];
        vectTit= new String[mat[0].length];
        
        for(int i=0;i<mat.length;i++){
            for(int j=0;j<mat[0].length;j++){
                objMat[i][j]=mat[i][j];
            }
        }
        DefaultTableModel objDefaultTableModel= new DefaultTableModel(objMat,vectTit);
        tblListar.setModel(objDefaultTableModel);
    }
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String codigo="0";
        String nombre="nombre";
        String codigoPais = "Codigo pais";
        String rutaNombre = "Ruta Y Nombre";
        
        if(!txfCodigo.getText().isEmpty())
            codigo=txfCodigo.getText();
        if(!txfNombre.getText().isEmpty())
            nombre=txfNombre.getText();
        if(!txfCodigoPais.getText().isEmpty())
            codigoPais=txfCodigoPais.getText();
        if(!txfRutaNombre.getText().isEmpty())
            rutaNombre=txfRutaNombre.getText();
        Ciudad objCiudad = new Ciudad(codigo, nombre, codigoPais, rutaNombre);
        controlCiudad objControlCiudad = new controlCiudad(objCiudad);
        objControlCiudad.modificar();
        this.listar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String codigo = txfCodigo.getText();
        Ciudad objCiudad = new Ciudad(codigo, "", "", "");
        controlCiudad objControlCiudad = new controlCiudad(objCiudad);
        objControlCiudad.borrar();
        this.listar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigo = txfCodigo.getText();
        Ciudad objCiudad = new Ciudad(codigo,"","","");
        controlCiudad objControlCiudad = new controlCiudad(objCiudad);
        objCiudad = objControlCiudad.consultar();
        txfNombre.setText(objCiudad.getNombre());
        txfCodigoPais.setText(objCiudad.getCodigoPais());
        txfRutaNombre.setText(objCiudad.getRutaNombre());
        this.listar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String codigo="0";
        String nombre="nombre";
        String codigoPais = "Codigo pais";
        String rutaNombre = "Ruta y nombre";
        //Extraccion de datos de la vista
        if (!txfCodigo.getText().isEmpty())
            codigo = txfCodigo.getText();
        if (!txfNombre.getText().isEmpty()) 
            nombre = txfNombre.getText();
        if (!txfCodigoPais.getText().isEmpty())
            codigoPais = txfCodigoPais.getText();
        if (!txfRutaNombre.getText().isEmpty()) 
            rutaNombre = txfRutaNombre.getText();
        
        Ciudad objCiudad = new Ciudad(codigo, nombre, codigoPais, rutaNombre);
        controlCiudad objControlCiudad = new controlCiudad(objCiudad);
        objControlCiudad.guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        new vistaPrincipal().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnRutaNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaNombreActionPerformed
        JFileChooser fc = new JFileChooser();//DECLARAR EL FILE CHOOSER
        fc.setDialogTitle("BUSCAR FOTO O IMAGEN");//TITULO PARA LA VENTANA QUE SE ABRIRA
        
        if(fc.showOpenDialog(this)==JFileChooser.APPROVE_OPTION){//SI PRESIONA ACEPTAR ENTRE EN LA CONDICION
            File Archivo = new File(fc.getSelectedFile().toString());
            txfRutaNombre.setText(Archivo.toString());
        }
    }//GEN-LAST:event_btnRutaNombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCiudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnRutaNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoPais;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblListar;
    private javax.swing.JTextField txfCodigo;
    private javax.swing.JTextField txfCodigoPais;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfRutaNombre;
    // End of variables declaration//GEN-END:variables
}
