package vista;

import control.*;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import modelo.*;
/**
 *
 * @author john
 */
public class vistaJugar extends javax.swing.JFrame {
    int contador =0;
    Ciudad objCiudad;
    /**
     * Creates new form vistaJugar
     */
    public vistaJugar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        lblJugar = new javax.swing.JLabel();
        lblCiudad = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        txfCiudad = new javax.swing.JTextField();
        txfPais = new javax.swing.JTextField();
        btnJugar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        btnValidar = new javax.swing.JButton();
        lblRespuesta = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblJugar.setText("JUGAR");
        getContentPane().add(lblJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 12, -1, -1));

        lblCiudad.setText("Ciudad:");
        getContentPane().add(lblCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 54, -1, -1));

        lblPais.setText("Pais:");
        getContentPane().add(lblPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 102, -1, -1));
        getContentPane().add(txfCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 48, 218, -1));
        getContentPane().add(txfPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 96, 218, -1));

        btnJugar.setText("Jugar");
        btnJugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarActionPerformed(evt);
            }
        });
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 144, -1, -1));
        getContentPane().add(lblImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 234, 223, 124));

        btnValidar.setText("Validar");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });
        getContentPane().add(btnValidar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 144, -1, -1));
        getContentPane().add(lblRespuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 370, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 144, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        controlJugar objControlJugar = new controlJugar();
        objCiudad = objControlJugar.saleccionarCiudad();
        txfCiudad.setText(objCiudad.getNombre());
    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
        controlJugar objControlJugar = new controlJugar();
        boolean respuesta;
        if (contador<3) {
            respuesta = objControlJugar.validarPais(objCiudad, txfPais.getText());
            if (respuesta) {
                String ruta = new File (objCiudad.getRutaNombre()).getAbsolutePath();
                Image img= new ImageIcon(ruta).getImage();
                ImageIcon img2=new ImageIcon(img.getScaledInstance(223, 124, Image.SCALE_SMOOTH));
                lblImagen.setIcon(img2);
                lblRespuesta.setText("Ganaste!");
            } else {
               txfPais.setText("");
               lblRespuesta.setText("Intenta de nuevo");
            }
        }else{
            Image img= new ImageIcon(objCiudad.getRutaNombre()).getImage();
            ImageIcon img2=new ImageIcon(img.getScaledInstance(223, 124, Image.SCALE_SMOOTH));
            lblImagen.setIcon(img2);
            lblRespuesta.setText("Fallaste");
        }
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        this.setVisible(false);
        new vistaPrincipal().setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaJugar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaJugar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblJugar;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JTextField txfCiudad;
    private javax.swing.JTextField txfPais;
    // End of variables declaration//GEN-END:variables
}
