/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.controlCiudad;
import javax.swing.table.DefaultTableModel;
import modelo.Ciudad;

/**
 *
 * @author john
 */
public class vistaCiudad extends javax.swing.JFrame {

    /**
     * Creates new form vistaCiudad
     */
    public vistaCiudad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCiudad = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        txfCodigo = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txfNombre = new javax.swing.JTextField();
        lblCodigoPais = new javax.swing.JLabel();
        txfCodigoPais = new javax.swing.JTextField();
        lblRutaNombre = new javax.swing.JLabel();
        txfRutaNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListar = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCiudad.setText("CIUDAD");

        lblCodigo.setText("Codigo:");

        lblNombre.setText("Nombre:");

        lblCodigoPais.setText("Coigo país:");

        lblRutaNombre.setText("Ruta y Nombre:");

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        tblListar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblListar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(lblCiudad))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar)
                        .addGap(12, 12, 12)
                        .addComponent(btnBorrar)
                        .addGap(12, 12, 12)
                        .addComponent(btnModificar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRutaNombre)
                                    .addComponent(lblCodigoPais)
                                    .addComponent(lblNombre)
                                    .addComponent(lblCodigo))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                                    .addComponent(txfCodigoPais, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txfCodigo)
                                    .addComponent(txfRutaNombre, javax.swing.GroupLayout.Alignment.LEADING))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCiudad)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigoPais)
                    .addComponent(txfCodigoPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutaNombre)
                    .addComponent(txfRutaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnBuscar)
                    .addComponent(btnBorrar)
                    .addComponent(btnModificar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void listar(){
        Object[][] objMat;
        String[] vectTit;
        Ciudad objCiudad = new Ciudad("", "", "", "");
        control.controlCiudad objControlCiudad = new controlCiudad(objCiudad);
        String[][] mat=objControlCiudad.listar();
        
        objMat= new Object[mat.length][mat[0].length];
        vectTit= new String[mat[0].length];
        
        for(int i=0;i<mat.length;i++){
            for(int j=0;j<mat[0].length;j++){
                objMat[i][j]=mat[i][j];
            }
        }
        DefaultTableModel objDefaultTableModel= new DefaultTableModel(objMat,vectTit);
        tblListar.setModel(objDefaultTableModel);
    }
    
    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String codigo="0";
        String nombre="nombre";
        String codigoPais = "Codigo pais";
        String rutaNombre = "Ruta Y Nombre";
        
        if(!txfCodigo.getText().isEmpty())
            codigo=txfCodigo.getText();
        if(!txfNombre.getText().isEmpty())
            nombre=txfNombre.getText();
        if(!txfCodigoPais.getText().isEmpty())
            codigoPais=txfCodigoPais.getText();
        if(!txfRutaNombre.getText().isEmpty())
            rutaNombre=txfRutaNombre.getText();
        Ciudad objCiudad = new Ciudad(codigo, nombre, codigoPais, rutaNombre);
        controlCiudad objControlCiudad = new controlCiudad(objCiudad);
        objControlCiudad.modificar();
        this.listar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        String codigo = txfCodigo.getText();
        Ciudad objCiudad = new Ciudad(codigo, "", "", "");
        controlCiudad objControlCiudad = new controlCiudad(objCiudad);
        objControlCiudad.borrar();
        this.listar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigo = txfCodigo.getText();
        Ciudad objCiudad = new Ciudad(codigo,"","","");
        controlCiudad objControlCiudad = new controlCiudad(objCiudad);
        objCiudad = objControlCiudad.consultar();
        txfNombre.setText(objCiudad.getNombre());
        txfCodigoPais.setText(objCiudad.getCodigoPais());
        txfRutaNombre.setText(objCiudad.getRutaNombre());
        this.listar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        String codigo="0";
        String nombre="nombre";
        String codigoPais = "Codigo pais";
        String rutaNombre = "Ruta y nombre";
        //Extraccion de datos de la vista
        if (!txfCodigo.getText().isEmpty())
            codigo = txfCodigo.getText();
        if (!txfNombre.getText().isEmpty()) 
            nombre = txfNombre.getText();
        if (!txfCodigoPais.getText().isEmpty())
            codigoPais = txfCodigoPais.getText();
        if (!txfRutaNombre.getText().isEmpty()) 
            rutaNombre = txfRutaNombre.getText();
        
        Ciudad objCiudad = new Ciudad(codigo, nombre, codigoPais, rutaNombre);
        controlCiudad objControlCiudad = new controlCiudad(objCiudad);
        objControlCiudad.guardar();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaCiudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCiudad;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblCodigoPais;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRutaNombre;
    private javax.swing.JTable tblListar;
    private javax.swing.JTextField txfCodigo;
    private javax.swing.JTextField txfCodigoPais;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfRutaNombre;
    // End of variables declaration//GEN-END:variables
}
